# Generated by Django 2.2.6 on 2019-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0055_auto_20190912_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentualStandardCotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_percentual', models.IntegerField(default=100, verbose_name='Percentual Casa')),
                ('tie_percentual', models.IntegerField(default=100, verbose_name='Percentual Empate')),
                ('away_percentual', models.IntegerField(default=100, verbose_name='Percentual Fora')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
