# Generated by Django 2.2.6 on 2019-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0057_percentualstandardcotation_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentualstandardcotation',
            name='away_percentual',
            field=models.IntegerField(null=True, verbose_name='Percentual Fora'),
        ),
        migrations.AlterField(
            model_name='percentualstandardcotation',
            name='home_percentual',
            field=models.IntegerField(null=True, verbose_name='Percentual Casa'),
        ),
        migrations.AlterField(
            model_name='percentualstandardcotation',
            name='tie_percentual',
            field=models.IntegerField(null=True, verbose_name='Percentual Empate'),
        ),
    ]
