# Generated by Django 3.0 on 2020-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0058_auto_20191009_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='separate_gross_and_net_value',
            field=models.BooleanField(default=False, verbose_name='Separar Bruto do Líquido'),
        ),
    ]
