# Generated by Django 2.2.7 on 2020-03-29 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0059_generalconfigurations_separate_gross_and_net_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
        migrations.AddField(
            model_name='entry',
            name='creator_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_entries', to=settings.AUTH_USER_MODEL, verbose_name='Quem gerou o lançamento'),
        ),
    ]
