# Generated by Django 2.2.7 on 2020-03-20 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0036_manager_can_close_cashier'),
        ('core', '0054_gamemodified_is_in_zone'),
        ('history', '0024_cashiercloseseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierCloseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=utils.timezone.now, verbose_name='Data da Transação')),
                ('start_date', models.DateTimeField(verbose_name='Data Início')),
                ('end_date', models.DateTimeField(verbose_name='Data Fim')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_closed_cashiers', to='user.Manager', verbose_name='Gerente em questão')),
                ('register_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Quem prestou conta')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca')),
            ],
            options={
                'verbose_name': 'Fechamento - Gerente',
                'verbose_name_plural': 'Fechamentos - Gerentes',
                'ordering': ('-id',),
            },
        ),
    ]
